# Generated by Django 4.2.27 on 2025-12-06 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('ndvi', 'NDVI Analysis (Leak Detection)'), ('change', 'Change Detection'), ('encroachment', 'Encroachment Detection'), ('emission', 'Emissions Tracking'), ('facility', 'Facility Monitoring')], max_length=20, verbose_name='analysis type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('progress', models.IntegerField(default=0, verbose_name='progress')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('chunks_total', models.IntegerField(default=0, verbose_name='total chunks')),
                ('chunks_processed', models.IntegerField(default=0, verbose_name='chunks processed')),
                ('processing_time_seconds', models.FloatField(blank=True, null=True, verbose_name='processing time (seconds)')),
                ('summary', models.TextField(blank=True, help_text='Human-readable summary of analysis results', verbose_name='summary')),
                ('severity', models.CharField(blank=True, help_text='Overall severity of findings', max_length=10, verbose_name='severity')),
                ('result_data', models.JSONField(blank=True, help_text='Detailed analysis results in JSON format', null=True, verbose_name='result data')),
                ('result_geojson', models.JSONField(blank=True, help_text='GeoJSON representation of detected features', null=True, verbose_name='result GeoJSON')),
                ('result_image', models.ImageField(blank=True, help_text='Visualization of analysis results', null=True, upload_to='analysis_results/', verbose_name='result image')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'analysis result',
                'verbose_name_plural': 'analysis results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeakDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.JSONField(help_text='Coordinates {lng, lat}', verbose_name='location')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='location name')),
                ('ndvi_value', models.FloatField(verbose_name='NDVI value')),
                ('confidence', models.FloatField(verbose_name='confidence score')),
                ('extent_sqm', models.FloatField(blank=True, null=True, verbose_name='extent (sq meters)')),
                ('severity', models.CharField(max_length=10, verbose_name='severity')),
                ('description', models.TextField(verbose_name='description')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='detected at')),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leak_detections', to='analysis.analysisresult')),
            ],
            options={
                'verbose_name': 'leak detection',
                'verbose_name_plural': 'leak detections',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.JSONField(help_text='Coordinates {lng, lat}', verbose_name='location')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='location name')),
                ('facility_type', models.CharField(choices=[('pipeline_segment', 'Pipeline Segment'), ('valve_station', 'Valve Station'), ('pump_station', 'Pump Station'), ('storage_tank', 'Storage Tank'), ('access_road', 'Access Road'), ('other', 'Other')], max_length=20, verbose_name='facility type')),
                ('condition', models.CharField(choices=[('normal', 'Normal'), ('minor_issue', 'Minor Issue'), ('moderate_issue', 'Moderate Issue'), ('severe_issue', 'Severe Issue'), ('critical', 'Critical')], max_length=20, verbose_name='condition')),
                ('confidence', models.FloatField(verbose_name='confidence score')),
                ('segmentation_mask', models.JSONField(blank=True, help_text='Segmentation polygon coordinates', null=True, verbose_name='segmentation mask')),
                ('area_sqm', models.FloatField(blank=True, null=True, verbose_name='area (sq meters)')),
                ('severity', models.CharField(max_length=10, verbose_name='severity')),
                ('description', models.TextField(verbose_name='description')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='detected at')),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_monitoring', to='analysis.analysisresult')),
            ],
            options={
                'verbose_name': 'facility monitoring',
                'verbose_name_plural': 'facility monitoring',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='EncroachmentDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.JSONField(help_text='Coordinates {lng, lat}', verbose_name='location')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='location name')),
                ('object_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('building', 'Building'), ('equipment', 'Equipment'), ('person', 'Person'), ('animal', 'Animal'), ('structure', 'Structure'), ('other', 'Other')], max_length=20, verbose_name='object type')),
                ('object_label', models.CharField(max_length=100, verbose_name='object label')),
                ('confidence', models.FloatField(verbose_name='confidence score')),
                ('bounding_box', models.JSONField(help_text='Bounding box coordinates', verbose_name='bounding box')),
                ('distance_to_pipeline_m', models.FloatField(blank=True, null=True, verbose_name='distance to pipeline (meters)')),
                ('severity', models.CharField(max_length=10, verbose_name='severity')),
                ('description', models.TextField(verbose_name='description')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='detected at')),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encroachment_detections', to='analysis.analysisresult')),
            ],
            options={
                'verbose_name': 'encroachment detection',
                'verbose_name_plural': 'encroachment detections',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.JSONField(help_text='Coordinates {lng, lat}', verbose_name='location')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='location name')),
                ('emission_type', models.CharField(choices=[('methane', 'Methane'), ('co2', 'Carbon Dioxide'), ('smoke', 'Smoke/Particulates'), ('heat', 'Heat Anomaly'), ('other', 'Other')], max_length=20, verbose_name='emission type')),
                ('intensity', models.FloatField(verbose_name='intensity')),
                ('confidence', models.FloatField(verbose_name='confidence score')),
                ('estimated_volume', models.FloatField(blank=True, help_text='Estimated emission volume in kg/day', null=True, verbose_name='estimated volume')),
                ('severity', models.CharField(max_length=10, verbose_name='severity')),
                ('description', models.TextField(verbose_name='description')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='detected at')),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_detections', to='analysis.analysisresult')),
            ],
            options={
                'verbose_name': 'emission detection',
                'verbose_name_plural': 'emission detections',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.JSONField(help_text='Coordinates {lng, lat}', verbose_name='location')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='location name')),
                ('change_type', models.CharField(choices=[('vegetation_loss', 'Vegetation Loss'), ('vegetation_gain', 'Vegetation Gain'), ('construction', 'New Construction'), ('erosion', 'Erosion'), ('water_change', 'Water Level Change'), ('unknown', 'Unknown Change')], max_length=20, verbose_name='change type')),
                ('change_percentage', models.FloatField(verbose_name='change percentage')),
                ('confidence', models.FloatField(verbose_name='confidence score')),
                ('area_sqm', models.FloatField(blank=True, null=True, verbose_name='area (sq meters)')),
                ('severity', models.CharField(max_length=10, verbose_name='severity')),
                ('description', models.TextField(verbose_name='description')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='detected at')),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_detections', to='analysis.analysisresult')),
            ],
            options={
                'verbose_name': 'change detection',
                'verbose_name_plural': 'change detections',
                'ordering': ['-detected_at'],
            },
        ),
    ]
