# Generated by Django 4.2.27 on 2025-12-06 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='satellite_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='pipeline.satelliteimage'),
        ),
        migrations.AlterUniqueTogether(
            name='analysisresult',
            unique_together={('satellite_image', 'analysis_type')},
        ),
    ]
