# Generated by Django 4.2.27 on 2025-12-06 08:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pipeline.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('geojson_file', models.FileField(upload_to=pipeline.models.pipeline_geojson_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['geojson', 'json'])], verbose_name='GeoJSON file')),
                ('geojson_data', models.JSONField(blank=True, null=True, verbose_name='GeoJSON data')),
                ('total_length_km', models.FloatField(blank=True, null=True, verbose_name='total length (km)')),
                ('start_point', models.JSONField(blank=True, null=True, verbose_name='start point')),
                ('end_point', models.JSONField(blank=True, null=True, verbose_name='end point')),
                ('bounds', models.JSONField(blank=True, help_text='Bounding box [minLng, minLat, maxLng, maxLat]', null=True, verbose_name='bounds')),
                ('color', models.CharField(default='#FF5722', max_length=7, verbose_name='display color')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_routes', to='user.organization')),
            ],
            options={
                'verbose_name': 'pipeline route',
                'verbose_name_plural': 'pipeline routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('original_file', models.FileField(help_text='Upload TIFF/GeoTIFF files only', upload_to=pipeline.models.satellite_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tif', 'tiff', 'TIF', 'TIFF'])], verbose_name='original image')),
                ('cog_file', models.FileField(blank=True, null=True, upload_to=pipeline.models.cog_image_path, verbose_name='Cloud Optimized GeoTIFF')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='acquisition date')),
                ('satellite_name', models.CharField(blank=True, max_length=100, verbose_name='satellite name')),
                ('resolution', models.FloatField(blank=True, null=True, verbose_name='resolution (m/pixel)')),
                ('bounds', models.JSONField(blank=True, help_text='Bounding box [minLng, minLat, maxLng, maxLat]', null=True, verbose_name='bounds')),
                ('center', models.JSONField(blank=True, help_text='Center point {lng, lat}', null=True, verbose_name='center')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='width (pixels)')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='height (pixels)')),
                ('bands', models.IntegerField(blank=True, null=True, verbose_name='number of bands')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='file size (bytes)')),
                ('crs', models.CharField(blank=True, max_length=100, verbose_name='coordinate reference system')),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='uploading', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('is_analyzed', models.BooleanField(default=False, verbose_name='is analyzed')),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='analysis completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_images', to='user.organization')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satellite_images', to='pipeline.pipelineroute')),
            ],
            options={
                'verbose_name': 'satellite image',
                'verbose_name_plural': 'satellite images',
                'ordering': ['-acquisition_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('leak', 'Leak Detected'), ('change', 'Change Detected'), ('encroachment', 'Encroachment Detected'), ('emission', 'Emission Detected'), ('facility', 'Facility Issue'), ('system', 'System Alert')], max_length=20, verbose_name='alert type')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10, verbose_name='severity')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('location', models.JSONField(blank=True, help_text='Location coordinates {lng, lat}', null=True, verbose_name='location')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='location name')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='is acknowledged')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='acknowledged at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='user.organization')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='pipeline.pipelineroute')),
                ('satellite_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='pipeline.satelliteimage')),
            ],
            options={
                'verbose_name': 'alert',
                'verbose_name_plural': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
